meta_product_name: "Helpr"
meta_title: "Helpr | Find Help in Your Local Community"
meta_description: "We help people connect to volunteer locally"
meta_image: "helprfb.jpg" # should exist in `app/assets/images/`
